### PR TITLE
Re-add coolapk and coolapk_coin

### PR DESCRIPTION
**Pull request by Rickrollcc**
第二次修改和上传

### CODE REVIEW

**Comment by Rickrollcc** [comment]
Screenshot_2024-09-12-19-38-41-107_com microsoft emmx
Screenshot_2024-09-12-19-38-43-140_com microsoft emmx

**Comment by Mister-Hope** [comment]
Cold you please update the main readme file as well？

**Comment by Rickrollcc** [comment]
> Cold you please update the main readme file as well？

The readme has been modified. I also modified the two newly added emojis readme and the first readme.

**Comment by Rickrollcc** [comment]
> Cold you please update the main readme file as well？

hello？

**Pull request merged**
