### PR TITLE
add new emojis

### PR DESCRIPTION
**Pull request by morannlx**
增加酷安表情包

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Maybe coolapk or at least cool as prefix?

**Comment by morannlx** [comment]
> Maybe coolapk or at least cool as prefix?

前缀是c_也就是coolapk的首字母，图省事就没改成coolapk

**Comment by Rickrollcc** [comment]
兄弟，很抱歉打扰你，不过已经差不多帮你完成这个目标了

**Comment by Mister-Hope** [comment]
Supported in 1.3.0

**Pull request closed without merging**
