### PR TITLE
add coolapk emoji

### PR DESCRIPTION
**Pull request by Rickrollcc**
添加酷安表情
add coolapk emoji

Screenshot_2024-09-12-00-33-00-478_com microsoft emmx

### CODE REVIEW

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
1. Some images are in wrong folder
2. No info.json is provided

**Comment by Rickrollcc** [comment]
I just checked and I didn't find any errors. I also provided info.json. If there are any errors, I will make changes

**Comment by Mister-Hope** [comment]
In review mode, some of the images are outside coolapk folder:
image

Also there are still Chinese names like lvyaowan, which could be green-pill

**Comment by Mister-Hope** [comment]
besides, I believe those coins could be deleted. They are not commonly used in normal communication.

**Comment by Mister-Hope** [comment]
And I think you can resort them by their frequency in coolapk apps.

**Comment by Rickrollcc** [comment]
okay

**Comment by Mister-Hope** [comment]
Note, I think the ca coin can be remained, you can also choose to remain some coins, but I believe we do not need all of them.

**Comment by Rickrollcc** [comment]
> Note, I think the ca coin can be remained, you can also choose to remain some coins, but I believe we do not need all of them.

Hi! I submitted the pull request again.
https://github.com/walinejs/emojis/pull/7

**Pull request closed without merging**
